facilities = {
            'olisar': 'Port Olisar',
            'grim': 'GrimHEX',
            'arc157': 'ArcCorp Mining Area 157',
            'benson': 'Benson Mining Outpost',
            'deakins': 'Deakins Research Outpost',
            'jump': 'Jumptown',
            'kudre': 'Kudre Ore',
            'arc141': 'ArcCorp Mining Area 141',
            'bountiful': 'Bountiful Harvest Hydroponics',
            'shubin': 'Shubin Mining Facility SCD-1',
            'tram': 'Tram & Myers Mining',
            'gallete': 'Gallete Family Farms',
            'terra': 'Terra Mills HydroFarm',
            'hickes': 'Hickes Research Outpost',
            'rrcru1': 'R&R CRU-L1',
            'rrcru4': 'R&R CRU-L4',
            'rrcru5': 'R&R CRU-L4',
            'levski': 'Levski',
            'lorville': 'Lorville',
            'cbd': 'CBD',
            'edmond': 'HDMS-Edmond',
            'hadley': 'HDMS-Hadley',
            'oparei': 'HDMS-Oparei',
            'pinewood': 'HDMS-Pinewood',
            'stanhope': 'HDMS-Stanhope',
            'thedus': 'HDMS-Thedus',
            'anderson': 'HDMS-Anderson',
            'norgaard': 'HDMS-Norgaard',
            'bezdek': 'HDMS-Bezdek',
            'lathan': 'HDMS-Lathan',
            'ryder': 'HDMS-Ryder',
            'woodruff': 'HDMS-Woodruff',
            'hahn': 'HDMS-Hahn',
            'perlman': 'HDMS-Perlman',
            'rrhur1': 'R&R HUR-L1',
            'rrhur2': 'R&R HUR-L2',
            'rrhur3': 'R&R HUR-L3',
            'rrhur4': 'R&R HUR-L4',
            'rrhur5': 'R&R HUR-L5'
            }

items = {
        'agi': 'Agricium',
        'as': 'Agricultural Supplies',
        'alt': 'Altruciatoxine',
        'alu': 'Aluminum',
        'ast': 'Astatine',
        'ber': 'Beryl',
        'chl': 'Chlorine',
        'cor': 'Corundum',
        'dia': 'Diamond',
        'ds': 'Distilled Spirits',
        'flu': 'Fluorine',
        'gol': 'Gold',
        'hyd': 'Hydrogen',
        'iod': 'Iodine',
        'lar': 'Laranite',
        'ms': 'Medical Supplies',
        'pf': 'Processed Food',
        'qua': 'Quartz',
        'scr': 'Scrap',
        'sti': 'Stims',
        'tit': 'Titanium',
        'tun': 'Tungsten',
        'was': 'Waste',
        'wid': 'WiDoW'
        }